# 3. Time series Analysis


## Contents
    1. Introduction
    2. Numpy
        1. Arange
        2. Zeroes
        3. One's
        4. Linspace
        5. Identity Matrix
        6. Random Data
            1. Uniform Distribution
    3. Time Series with Pandas
        1. DateTime Index


## Introduction

Some of the things that will be covered in the notes:

 - Understand how to use Python to work with Time Series Data
    - will use Pandas and Stats Models to create predictive models
 - Will also have some Numpy Basics
 - Look at the specific Time Series tools that is included with Pandas
 - Stats Models has a full Time Series sections
 - Will look at General Forecasting Models (Looking at ARIMA Models)
 - Look at Deep Learning and Prophet which is one of the latest methods for forecasting

## Numpy

For Majority of this section I will only be covering some useful methods that are included with Numpy and will assume that the users of these notes have knowledge of the creation and slicing of Numpy Array's


### Arange

This is a method that is useful to create a **Numpy Array** from a decided range of values.

While this may seem very basic at this point in time, this can also be done with Datetime data in order to create date values for Index's or other variables.

Let's have a look at how it works:

In [1]:
import numpy as np

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Zeros:

We may get to a point that we want a set of numbers that are only zeros and this can be done using the following method:

Note that the passed value is the size of the final Array that we are creating.

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

We can also create a turple of Zero's if this is required in our analysis:

In [3]:
np.zeros((4,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### One's:

Just like the method which created an array of Zero's we may need to have a situation where we require an array of all 1 values, this can be done with the ones method.

Just like the **Zeros** method the parssed value is the size of the Array:

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

### Linspace

We have seen that the **Arange** method will create an array with a starting point, ending point and increment but there are also cases where we want to have a equal spacing between the starting and ending point. This is where the **Linspace** method becomes useful.

With **Linspace** method, the final array will have the number of values equally spaced between the minimum and maximum values.

In [5]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Identity Matrix

While this is not used in Time Series analysis it is usefuly to know how to create an identity matrix for any analysis in the future.

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random Data

#### Uniform Distribution:

The first array we can create is one generated from a uniform distribution, the values will only be between 0 and 1:

In [7]:
np.random.rand(10)

array([0.86312332, 0.68895444, 0.59728198, 0.27420425, 0.48240303,
       0.66623771, 0.56496501, 0.7390307 , 0.48051096, 0.03212244])

#### Normal Distribution:

It may not be ideal to always have the distribution as a uniform distribtuion so there are other options to have the data calculated from other distributions.

The first of these distributions is the normal distribution, we can do it using the following method:

In [8]:
np.random.randn(10)

array([-0.31488287, -0.23944506, -0.67717257, -1.2756057 , -0.39020142,
        0.78740486,  0.73992456, -0.82648507,  0.10528124,  1.31600605])

### Random numbers between values:

In some cases we want to specify the values that the random values should be between this can be done using the method below:

In [9]:
np.random.randint(1,100,10)

array([31, 48, 55, 15, 72,  5, 62, 38, 15, 21])

### Setting the seed:

With most analysis that is required we need to ensure that the results are reproducable. The most important part of this is to use seeds when we are creating random values.

In [10]:
np.random.seed(42)

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In Jupyter we need to keep the seed in the same cell to ensure it is used for the random function.

We can now start with creating a few arrays to work with.

In [11]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

We may want to reshape an array at some point. So lets reshape the arr into a 5 x 5 array:

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We always need to ensure that the shape of the array makes sense in terms of the size of the array else there will be a error given.

We can also check for the maximum and minimum values within an array:

In [14]:
ranarr.max()

39

In [15]:
ranarr.min()

2

We can find the index location of the maximum and minimum of the array:

In [16]:
ranarr.argmax()

7

In [17]:
ranarr.argmin()

9

We can check the datatype of the values within the array with the following:

In [18]:
ranarr.dtype

dtype('int64')

### Indexing and selection:

Index gets a single element while selection is to get a slice.

Let's get an index from our array:

In [19]:
arr[8]

8

From a range:

In [20]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

We can also broadcast functions across our array:

In [21]:
arr +10


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

We can slice the array with the following:

In [22]:
slice_1 = arr[0:6]

slice_1

array([0, 1, 2, 3, 4, 5])

and now we can modify the slice:

In [23]:
slice_1 [:] = 99

slice_1

array([99, 99, 99, 99, 99, 99])

It is important to note that the slice is reffering to the original array as well:

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

to make a copy of an array we can use the copy method:

In [25]:
arr_copy = arr.copy()


arr_copy


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Time Series Data:

### Date time Index

Built into standard Python is the ability to create datetime values:

Let's try creating an object:

In [26]:
from datetime import datetime

my_year = 2020
my_month = 6
my_day = 18
my_hour = 16
my_min = 25
my_sec = 15

my_date =datetime(my_year,my_month,my_day)

my_date

datetime.datetime(2020, 6, 18, 0, 0)

Note that when all the elements are not included the rest of the objects are set to 0.


But if we define all of it:

In [27]:
my_date_time =datetime(my_year,my_month,my_day,my_hour,my_min,my_sec)

my_date_time

datetime.datetime(2020, 6, 18, 16, 25, 15)

we can now interact with these objects:

In [28]:
my_date_time.day


18

We can see what python has avaliable but what about numpy?

In [29]:
np.array(['2020-03-15','2020-03-16','2020-03-17'])

array(['2020-03-15', '2020-03-16', '2020-03-17'], dtype='<U10')

Numpy will treat this as normal strings but we can convert them:

In [30]:
np.array(['2020-03-15','2020-03-16','2020-03-17'],dtype='datetime64')

array(['2020-03-15', '2020-03-16', '2020-03-17'], dtype='datetime64[D]')

For extra control we can set the precision after datatime64 with square brackets:

In [31]:
np.array(['2020-03-15','2020-03-16','2020-03-17'],dtype='datetime64[Y]')


array(['2020', '2020', '2020'], dtype='datetime64[Y]')

we can also use ranges to create a list of dates:

In [32]:
np.arange('2018-06-01','2018-06-23',7,dtype='datetime64[D]')

array(['2018-06-01', '2018-06-08', '2018-06-15', '2018-06-22'],
      dtype='datetime64[D]')

This can also be done with Pandas as it is built off the Numpy foundation.

Pandas also has some built in utilites to handle date time variables

In [33]:
import pandas as pd

pd.date_range('2020-01-01',periods=7,freq='D')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')

we will now get a date time index from these values and it will be aware of the datetime variable type

Pandas is also really good at infering string codes:

In [34]:
pd.date_range('Jan 01, 2018',periods=7,freq='D')

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07'],
              dtype='datetime64[ns]', freq='D')

this needs to be in the specific formats that are built into Pandas but it will generally work.

We can also use a to date time with the format:

In [35]:
pd.to_datetime(['1/2/2018','Jan 03, 2018'])

DatetimeIndex(['2018-01-02', '2018-01-03'], dtype='datetime64[ns]', freq=None)

This will convert these into date times.

If we need to deal with the inverse of the American order or data that is in the other format we can specify the format:

In [36]:
pd.to_datetime(['1/2/2018','1/3/2018'],format='%d/%m/%Y')

DatetimeIndex(['2018-02-01', '2018-03-01'], dtype='datetime64[ns]', freq=None)

This will now calculate the date format that should be in day month year format

Lets have a look at pandas date time analysis with random data:

In [37]:
data = np.random.randn(3,2)

data

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024]])

In [38]:
idx = pd.date_range('2020-01-01',periods=3,freq='D')
cols=['A','B']
df = pd.DataFrame(data,index=idx,columns=cols)

In [39]:
df.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03'], dtype='datetime64[ns]', freq='D')

In [40]:
df.index.max()

Timestamp('2020-01-03 00:00:00', freq='D')

In [41]:
df.index.argmax()

2

### Time Resampling

This is almost like grouping data together but this is almost like using functions across the data.

Lets start by importing the data we will be working with:

We will also set the index to the data and refence it as a date time

In [42]:
df = pd.read_csv('Data\\starbucks.csv',index_col='Date',parse_dates=True)

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Data\\starbucks.csv'

In [ ]:
df.index

We can see that the data is daily data but missing weekend information. We can resample this off a rule.

In [ ]:
df.resample(rule='D').sum()

this is along the same lines as group by except there are rules that can be applied to the data when it is grouping the data by the functions.

We can combine resampling with plotting:

In [ ]:
%matplotlib inline
df['Close'].resample('M').mean().plot.bar(title = 'Yearly closing price Means')

### Time Shifting

We may need to shift the data up and down along the time series index. we will still be using the Starbucks data file.

In [ ]:
df.head()

In [ ]:
df.tail()

We can shift using the shift Method:

In [ ]:
df.shift(1)

This will move all of the data points up one point but this will leave us with an empty data point in the front and the loss of the final row.

this can also be done using a negative number to shift everything back one date.

This can also be done using time series frequency codes:

In [ ]:
df.shift(periods=1,freq='M')

### Rolling and Expanding

This is a way of grouping the data into windows of time and then apply an aggregate of time.


We will plot the data first with no rolling mean:

In [ ]:
%matplotlib inline
df['Close'].plot(figsize=(12,5))


In [ ]:
df.rolling(window=7).mean()

Window is how large the section we want to look at usually in days. this calculates the moving average from the last x days

In [ ]:
%matplotlib inline
df['Close'].plot(figsize=(12,5))
df.rolling(window=7).mean()['Close'].plot()

we can also do expanding - this is to consider all prior data in our ever expanding data set.

In [ ]:
%matplotlib inline
df['Close'].expanding().mean().plot(figsize=(12,5))


### Rolling and Expanding

This is a way of grouping the data into windows of time and then apply an aggregate of time.


We will plot the data first with no rolling mean:

In [ ]:
%matplotlib inline
df['Close'].plot(figsize=(12,5))


In [ ]:
df.rolling(window=7).mean()

Window is how large the section we want to look at usually in days. this calculates the moving average from the last x days

In [ ]:
%matplotlib inline
df['Close'].plot(figsize=(12,5))
df.rolling(window=7).mean()['Close'].plot()

we can also do expanding - this is to consider all prior data in our ever expanding data set.

In [ ]:
df['close'].expanding().mean().plot(figsize=(12,5))

This should start to average off eventually due to the ever increasing data that is included with the method.
